[workspace]

members = [
    "modules",
    "relayer",
    "relayer-cli",
    "telemetry",
    "proto",
]

exclude = [
    "proto-compiler"
]

# [patch.crates-io]
# tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
# tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
# tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
# tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }
# tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "master" }


#[patch.crates-io]
#tendermint              = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
#tendermint-rpc          = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
#tendermint-proto        = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
#tendermint-light-client = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
#tendermint-testgen      = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
#ics23                   = { git = "https://github.com/DaviRain-Su/ics23.git", branch = "suooprt-no-std" }

[patch.crates-io]
tendermint              = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
tendermint-rpc          = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
tendermint-proto        = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
tendermint-light-client = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
tendermint-testgen      = { git = "https://github.com/octopus-network/tendermint-rs.git", branch = "octpus-no-std-flex-error" }
ics23                   = { git = "https://github.com/DaviRain-Su/ics23.git", branch = "suooprt-no-std" }